// <auto-generated />
using System;
using AspNetCore_School_DataAccess_Layer.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AspNetCore_School_DataAccess_Layer.Migrations
{
    [DbContext(typeof(SchoolContext))]
    partial class SchoolContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("AspNetCore_School_DataAccess_Layer.Identity.AppRole", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("AspNetCore_School_DataAccess_Layer.Identity.AppUser", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("AspNetCore_School_Entity_Layer.Entities.Class", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("SchoolId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("SchoolId");

                    b.ToTable("Classes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Sınıf 1",
                            SchoolId = 1
                        },
                        new
                        {
                            Id = 2,
                            Name = "Sınıf 2",
                            SchoolId = 1
                        },
                        new
                        {
                            Id = 3,
                            Name = "Sınıf 3",
                            SchoolId = 1
                        },
                        new
                        {
                            Id = 4,
                            Name = "Sınıf 1",
                            SchoolId = 2
                        },
                        new
                        {
                            Id = 5,
                            Name = "Sınıf 2",
                            SchoolId = 2
                        },
                        new
                        {
                            Id = 6,
                            Name = "Sınıf 3",
                            SchoolId = 2
                        },
                        new
                        {
                            Id = 7,
                            Name = "Sınıf 1",
                            SchoolId = 3
                        },
                        new
                        {
                            Id = 8,
                            Name = "Sınıf 2",
                            SchoolId = 3
                        },
                        new
                        {
                            Id = 9,
                            Name = "Sınıf 3",
                            SchoolId = 3
                        });
                });

            modelBuilder.Entity("AspNetCore_School_Entity_Layer.Entities.School", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("District")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Schools");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            District = "Yeşilköy Mahallesi",
                            Name = "Bayrak Lisesi"
                        },
                        new
                        {
                            Id = 2,
                            District = "Merkez Mahallesi",
                            Name = "Güneş Lisesi"
                        },
                        new
                        {
                            Id = 3,
                            District = "Sahil Mahallesi",
                            Name = "Deniz Lisesi"
                        });
                });

            modelBuilder.Entity("AspNetCore_School_Entity_Layer.Entities.Student", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ClassId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SchoolNo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SurName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("ClassId");

                    b.ToTable("Students");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ClassId = 1,
                            Name = "Ahmet",
                            SchoolNo = "1001",
                            SurName = "Yılmaz"
                        },
                        new
                        {
                            Id = 2,
                            ClassId = 1,
                            Name = "Mehmet",
                            SchoolNo = "1002",
                            SurName = "Demir"
                        },
                        new
                        {
                            Id = 3,
                            ClassId = 1,
                            Name = "Ayşe",
                            SchoolNo = "1003",
                            SurName = "Kara"
                        },
                        new
                        {
                            Id = 4,
                            ClassId = 1,
                            Name = "Fatma",
                            SchoolNo = "1004",
                            SurName = "Kurt"
                        },
                        new
                        {
                            Id = 5,
                            ClassId = 1,
                            Name = "Mustafa",
                            SchoolNo = "1005",
                            SurName = "Taş"
                        },
                        new
                        {
                            Id = 6,
                            ClassId = 1,
                            Name = "Hatice",
                            SchoolNo = "1006",
                            SurName = "Aydın"
                        },
                        new
                        {
                            Id = 7,
                            ClassId = 1,
                            Name = "Ali",
                            SchoolNo = "1007",
                            SurName = "Yıldırım"
                        },
                        new
                        {
                            Id = 8,
                            ClassId = 1,
                            Name = "Nur",
                            SchoolNo = "1008",
                            SurName = "Sarı"
                        },
                        new
                        {
                            Id = 9,
                            ClassId = 1,
                            Name = "Emir",
                            SchoolNo = "1009",
                            SurName = "Kara"
                        },
                        new
                        {
                            Id = 10,
                            ClassId = 1,
                            Name = "Ebru",
                            SchoolNo = "1010",
                            SurName = "Yılmaz"
                        },
                        new
                        {
                            Id = 11,
                            ClassId = 2,
                            Name = "Selin",
                            SchoolNo = "1011",
                            SurName = "Ateş"
                        },
                        new
                        {
                            Id = 12,
                            ClassId = 2,
                            Name = "Burak",
                            SchoolNo = "1012",
                            SurName = "Demir"
                        },
                        new
                        {
                            Id = 13,
                            ClassId = 2,
                            Name = "Zeynep",
                            SchoolNo = "1013",
                            SurName = "Kurt"
                        },
                        new
                        {
                            Id = 14,
                            ClassId = 2,
                            Name = "Kerem",
                            SchoolNo = "1014",
                            SurName = "Yılmaz"
                        },
                        new
                        {
                            Id = 15,
                            ClassId = 2,
                            Name = "Aslı",
                            SchoolNo = "1015",
                            SurName = "Taş"
                        },
                        new
                        {
                            Id = 16,
                            ClassId = 2,
                            Name = "Deniz",
                            SchoolNo = "1016",
                            SurName = "Sarı"
                        },
                        new
                        {
                            Id = 17,
                            ClassId = 2,
                            Name = "Cem",
                            SchoolNo = "1017",
                            SurName = "Aydın"
                        },
                        new
                        {
                            Id = 18,
                            ClassId = 2,
                            Name = "Elif",
                            SchoolNo = "1018",
                            SurName = "Kara"
                        },
                        new
                        {
                            Id = 19,
                            ClassId = 2,
                            Name = "Merve",
                            SchoolNo = "1019",
                            SurName = "Yıldırım"
                        },
                        new
                        {
                            Id = 20,
                            ClassId = 2,
                            Name = "Can",
                            SchoolNo = "1020",
                            SurName = "Ateş"
                        },
                        new
                        {
                            Id = 21,
                            ClassId = 3,
                            Name = "Ege",
                            SchoolNo = "1021",
                            SurName = "Kara"
                        },
                        new
                        {
                            Id = 22,
                            ClassId = 3,
                            Name = "Elif",
                            SchoolNo = "1022",
                            SurName = "Yılmaz"
                        },
                        new
                        {
                            Id = 23,
                            ClassId = 3,
                            Name = "Onur",
                            SchoolNo = "1023",
                            SurName = "Taş"
                        },
                        new
                        {
                            Id = 24,
                            ClassId = 3,
                            Name = "Yaren",
                            SchoolNo = "1024",
                            SurName = "Sarı"
                        },
                        new
                        {
                            Id = 25,
                            ClassId = 3,
                            Name = "Cemal",
                            SchoolNo = "1025",
                            SurName = "Demir"
                        },
                        new
                        {
                            Id = 26,
                            ClassId = 3,
                            Name = "Seda",
                            SchoolNo = "1026",
                            SurName = "Aydın"
                        },
                        new
                        {
                            Id = 27,
                            ClassId = 3,
                            Name = "Kaan",
                            SchoolNo = "1027",
                            SurName = "Kurt"
                        },
                        new
                        {
                            Id = 28,
                            ClassId = 3,
                            Name = "Rabia",
                            SchoolNo = "1028",
                            SurName = "Yıldırım"
                        },
                        new
                        {
                            Id = 29,
                            ClassId = 3,
                            Name = "Tolga",
                            SchoolNo = "1029",
                            SurName = "Sarı"
                        },
                        new
                        {
                            Id = 30,
                            ClassId = 3,
                            Name = "Aylin",
                            SchoolNo = "1030",
                            SurName = "Ateş"
                        },
                        new
                        {
                            Id = 31,
                            ClassId = 4,
                            Name = "Defne",
                            SchoolNo = "1031",
                            SurName = "Kara"
                        },
                        new
                        {
                            Id = 32,
                            ClassId = 4,
                            Name = "Arda",
                            SchoolNo = "1032",
                            SurName = "Yılmaz"
                        },
                        new
                        {
                            Id = 33,
                            ClassId = 4,
                            Name = "Selin",
                            SchoolNo = "1033",
                            SurName = "Demir"
                        },
                        new
                        {
                            Id = 34,
                            ClassId = 4,
                            Name = "Kerem",
                            SchoolNo = "1034",
                            SurName = "Taş"
                        },
                        new
                        {
                            Id = 35,
                            ClassId = 4,
                            Name = "Zeynep",
                            SchoolNo = "1035",
                            SurName = "Kurt"
                        },
                        new
                        {
                            Id = 36,
                            ClassId = 4,
                            Name = "Ali",
                            SchoolNo = "1036",
                            SurName = "Aydın"
                        },
                        new
                        {
                            Id = 37,
                            ClassId = 4,
                            Name = "Ela",
                            SchoolNo = "1037",
                            SurName = "Sarı"
                        },
                        new
                        {
                            Id = 38,
                            ClassId = 4,
                            Name = "Emir",
                            SchoolNo = "1038",
                            SurName = "Yıldırım"
                        },
                        new
                        {
                            Id = 39,
                            ClassId = 4,
                            Name = "Lina",
                            SchoolNo = "1039",
                            SurName = "Taş"
                        },
                        new
                        {
                            Id = 40,
                            ClassId = 4,
                            Name = "Aycan",
                            SchoolNo = "1040",
                            SurName = "Ateş"
                        },
                        new
                        {
                            Id = 41,
                            ClassId = 5,
                            Name = "Eren",
                            SchoolNo = "1041",
                            SurName = "Kara"
                        },
                        new
                        {
                            Id = 42,
                            ClassId = 5,
                            Name = "Ezgi",
                            SchoolNo = "1042",
                            SurName = "Yılmaz"
                        },
                        new
                        {
                            Id = 43,
                            ClassId = 5,
                            Name = "Alihan",
                            SchoolNo = "1043",
                            SurName = "Demir"
                        },
                        new
                        {
                            Id = 44,
                            ClassId = 5,
                            Name = "Sude",
                            SchoolNo = "1044",
                            SurName = "Taş"
                        },
                        new
                        {
                            Id = 45,
                            ClassId = 5,
                            Name = "Cemre",
                            SchoolNo = "1045",
                            SurName = "Kurt"
                        },
                        new
                        {
                            Id = 46,
                            ClassId = 5,
                            Name = "Kaan",
                            SchoolNo = "1046",
                            SurName = "Aydın"
                        },
                        new
                        {
                            Id = 47,
                            ClassId = 5,
                            Name = "Mina",
                            SchoolNo = "1047",
                            SurName = "Sarı"
                        },
                        new
                        {
                            Id = 48,
                            ClassId = 5,
                            Name = "Ayşenur",
                            SchoolNo = "1048",
                            SurName = "Yıldırım"
                        },
                        new
                        {
                            Id = 49,
                            ClassId = 5,
                            Name = "Kerim",
                            SchoolNo = "1049",
                            SurName = "Taş"
                        },
                        new
                        {
                            Id = 50,
                            ClassId = 5,
                            Name = "Lara",
                            SchoolNo = "1050",
                            SurName = "Ateş"
                        },
                        new
                        {
                            Id = 51,
                            ClassId = 6,
                            Name = "Selin",
                            SchoolNo = "2001",
                            SurName = "Kara"
                        },
                        new
                        {
                            Id = 52,
                            ClassId = 6,
                            Name = "Arda",
                            SchoolNo = "2002",
                            SurName = "Yılmaz"
                        },
                        new
                        {
                            Id = 53,
                            ClassId = 6,
                            Name = "Elif",
                            SchoolNo = "2003",
                            SurName = "Demir"
                        },
                        new
                        {
                            Id = 54,
                            ClassId = 6,
                            Name = "Kerem",
                            SchoolNo = "2004",
                            SurName = "Taş"
                        },
                        new
                        {
                            Id = 55,
                            ClassId = 6,
                            Name = "Zeynep",
                            SchoolNo = "2005",
                            SurName = "Kurt"
                        },
                        new
                        {
                            Id = 56,
                            ClassId = 6,
                            Name = "Ali",
                            SchoolNo = "2006",
                            SurName = "Aydın"
                        },
                        new
                        {
                            Id = 57,
                            ClassId = 6,
                            Name = "Ela",
                            SchoolNo = "2007",
                            SurName = "Sarı"
                        },
                        new
                        {
                            Id = 58,
                            ClassId = 6,
                            Name = "Emir",
                            SchoolNo = "2008",
                            SurName = "Yıldırım"
                        },
                        new
                        {
                            Id = 59,
                            ClassId = 6,
                            Name = "Lina",
                            SchoolNo = "2009",
                            SurName = "Taş"
                        },
                        new
                        {
                            Id = 60,
                            ClassId = 6,
                            Name = "Aycan",
                            SchoolNo = "2010",
                            SurName = "Ateş"
                        },
                        new
                        {
                            Id = 61,
                            ClassId = 7,
                            Name = "Mehmet",
                            SchoolNo = "2011",
                            SurName = "Kara"
                        },
                        new
                        {
                            Id = 62,
                            ClassId = 7,
                            Name = "Ceren",
                            SchoolNo = "2012",
                            SurName = "Yılmaz"
                        },
                        new
                        {
                            Id = 63,
                            ClassId = 7,
                            Name = "Oğuz",
                            SchoolNo = "2013",
                            SurName = "Demir"
                        },
                        new
                        {
                            Id = 64,
                            ClassId = 7,
                            Name = "Sude",
                            SchoolNo = "2014",
                            SurName = "Taş"
                        },
                        new
                        {
                            Id = 65,
                            ClassId = 7,
                            Name = "Cemre",
                            SchoolNo = "2015",
                            SurName = "Kurt"
                        },
                        new
                        {
                            Id = 66,
                            ClassId = 7,
                            Name = "Kaan",
                            SchoolNo = "2016",
                            SurName = "Aydın"
                        },
                        new
                        {
                            Id = 67,
                            ClassId = 7,
                            Name = "Ela",
                            SchoolNo = "2017",
                            SurName = "Sarı"
                        },
                        new
                        {
                            Id = 68,
                            ClassId = 7,
                            Name = "Emir",
                            SchoolNo = "2018",
                            SurName = "Yıldırım"
                        },
                        new
                        {
                            Id = 69,
                            ClassId = 7,
                            Name = "Lina",
                            SchoolNo = "2019",
                            SurName = "Taş"
                        },
                        new
                        {
                            Id = 70,
                            ClassId = 7,
                            Name = "Aycan",
                            SchoolNo = "2020",
                            SurName = "Ateş"
                        },
                        new
                        {
                            Id = 71,
                            ClassId = 8,
                            Name = "Selin",
                            SchoolNo = "2401",
                            SurName = "Kara"
                        },
                        new
                        {
                            Id = 72,
                            ClassId = 8,
                            Name = "Arda",
                            SchoolNo = "2402",
                            SurName = "Yılmaz"
                        },
                        new
                        {
                            Id = 73,
                            ClassId = 8,
                            Name = "Elif",
                            SchoolNo = "2403",
                            SurName = "Demir"
                        },
                        new
                        {
                            Id = 74,
                            ClassId = 8,
                            Name = "Kerem",
                            SchoolNo = "2404",
                            SurName = "Taş"
                        },
                        new
                        {
                            Id = 75,
                            ClassId = 8,
                            Name = "Zeynep",
                            SchoolNo = "2405",
                            SurName = "Kurt"
                        },
                        new
                        {
                            Id = 76,
                            ClassId = 8,
                            Name = "Ali",
                            SchoolNo = "2406",
                            SurName = "Aydın"
                        },
                        new
                        {
                            Id = 77,
                            ClassId = 8,
                            Name = "Ela",
                            SchoolNo = "2407",
                            SurName = "Sarı"
                        },
                        new
                        {
                            Id = 78,
                            ClassId = 8,
                            Name = "Emir",
                            SchoolNo = "2408",
                            SurName = "Yıldırım"
                        },
                        new
                        {
                            Id = 79,
                            ClassId = 8,
                            Name = "Lina",
                            SchoolNo = "2409",
                            SurName = "Taş"
                        },
                        new
                        {
                            Id = 80,
                            ClassId = 8,
                            Name = "Aycan",
                            SchoolNo = "2410",
                            SurName = "Ateş"
                        },
                        new
                        {
                            Id = 81,
                            ClassId = 9,
                            Name = "Eren",
                            SchoolNo = "2501",
                            SurName = "Kara"
                        },
                        new
                        {
                            Id = 82,
                            ClassId = 9,
                            Name = "Ezgi",
                            SchoolNo = "2502",
                            SurName = "Yılmaz"
                        },
                        new
                        {
                            Id = 83,
                            ClassId = 9,
                            Name = "Alihan",
                            SchoolNo = "2503",
                            SurName = "Demir"
                        },
                        new
                        {
                            Id = 84,
                            ClassId = 9,
                            Name = "Sude",
                            SchoolNo = "2504",
                            SurName = "Taş"
                        },
                        new
                        {
                            Id = 85,
                            ClassId = 9,
                            Name = "Cemre",
                            SchoolNo = "2505",
                            SurName = "Kurt"
                        },
                        new
                        {
                            Id = 86,
                            ClassId = 9,
                            Name = "Kaan",
                            SchoolNo = "2506",
                            SurName = "Aydın"
                        },
                        new
                        {
                            Id = 87,
                            ClassId = 9,
                            Name = "Mina",
                            SchoolNo = "2507",
                            SurName = "Sarı"
                        },
                        new
                        {
                            Id = 88,
                            ClassId = 9,
                            Name = "Ayşenur",
                            SchoolNo = "2508",
                            SurName = "Yıldırım"
                        },
                        new
                        {
                            Id = 89,
                            ClassId = 9,
                            Name = "Kerim",
                            SchoolNo = "2509",
                            SurName = "Taş"
                        },
                        new
                        {
                            Id = 90,
                            ClassId = 9,
                            Name = "Lara",
                            SchoolNo = "2510",
                            SurName = "Ateş"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<int>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<int>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<int>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<int>", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<int>", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("AspNetCore_School_Entity_Layer.Entities.Class", b =>
                {
                    b.HasOne("AspNetCore_School_Entity_Layer.Entities.School", "School")
                        .WithMany("Classes")
                        .HasForeignKey("SchoolId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("School");
                });

            modelBuilder.Entity("AspNetCore_School_Entity_Layer.Entities.Student", b =>
                {
                    b.HasOne("AspNetCore_School_Entity_Layer.Entities.Class", "Class")
                        .WithMany("Students")
                        .HasForeignKey("ClassId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Class");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<int>", b =>
                {
                    b.HasOne("AspNetCore_School_DataAccess_Layer.Identity.AppRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<int>", b =>
                {
                    b.HasOne("AspNetCore_School_DataAccess_Layer.Identity.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<int>", b =>
                {
                    b.HasOne("AspNetCore_School_DataAccess_Layer.Identity.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<int>", b =>
                {
                    b.HasOne("AspNetCore_School_DataAccess_Layer.Identity.AppRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AspNetCore_School_DataAccess_Layer.Identity.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<int>", b =>
                {
                    b.HasOne("AspNetCore_School_DataAccess_Layer.Identity.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("AspNetCore_School_Entity_Layer.Entities.Class", b =>
                {
                    b.Navigation("Students");
                });

            modelBuilder.Entity("AspNetCore_School_Entity_Layer.Entities.School", b =>
                {
                    b.Navigation("Classes");
                });
#pragma warning restore 612, 618
        }
    }
}
